"""initial schema

Revision ID: 273b75073ff6
Revises: 
Create Date: 2026-09-28 19:47:52.870355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '273b75073ff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('color_slot', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('native_name', sa.String(length=64), nullable=False),
    sa.Column('flag_emoji', sa.String(length=8), nullable=False),
    sa.Column('accent_color', sa.String(length=9), nullable=True),
    sa.Column('goal_level_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_level_id'], ['level.id'], name='fk_language_goal_level', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('target_hours', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'code', name='uq_level_language_code')
    )
    op.create_table('milestone_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('achieved_on', sa.Date(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_skill_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'activity_type_id', name='uq_level_activity')
    )
    op.create_table('plan_template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_template_weekday_range'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'PARTIAL', 'SKIPPED', name='planitemstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plan.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['plan_template_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_item_id', 'date', name='uq_plan_item_template_date')
    )
    with op.batch_alter_table('plan_item', schema=None) as batch_op:
        batch_op.create_index('ix_plan_item_plan_date', ['plan_id', 'date'], unique=False)

    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('plan_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('minutes > 0 AND minutes <= 960', name='ck_session_minutes_range'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_type.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_item_id')
    )
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index('ix_session_language_date', ['language_id', 'study_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_language_date')

    op.drop_table('study_session')
    with op.batch_alter_table('plan_item', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_item_plan_date')

    op.drop_table('plan_item')
    op.drop_table('plan_template_item')
    op.drop_table('level_skill_target')
    op.drop_table('study_plan')
    op.drop_table('milestone_event')
    op.drop_table('level')
    op.drop_table('setting')
    op.drop_table('language')
    op.drop_table('activity_type')
    # ### end Alembic commands ###
