"""add is_backfill to study_session

Revision ID: 58c992d33794
Revises: 273b75073ff6
Create Date: 2026-10-01 16:20:28.669372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c992d33794'
down_revision = '273b75073ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_backfill', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('is_backfill')

    # ### end Alembic commands ###
